source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'sqlite3'
gem 'jquery-rails'
gem 'paperclip', '3.4.0'
gem 'papercrop', :path => "../.."

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer'
  gem 'uglifier', '>= 1.0.3'
end

