source 'https://rubygems.org'

gem 'rails', '3.2.8'

gem 'jquery-rails'
gem 'execjs'
gem 'therubyracer'
gem 'sqlite3'
gem 'paperclip', '3.4.0'

gem 'papercrop', :path => ".."

gem "pry-debugger"
gem "pry-doc"

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier',     '>= 1.0.3'
end
