source 'https://rubygems.org'

gem 'rails', '~> 4.0.0'

gem 'jquery-rails'
gem 'execjs'
gem 'therubyracer'
gem 'sqlite3'
gem 'paperclip'

gem 'papercrop', :path => ".."

gem "pry-debugger"
gem "pry-doc"

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end
