source 'https://rubygems.org'

gem 'rails', '4.0.2'
gem 'shared_rails', :path => "../shared_rails"
gem 'sqlite3'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'paperclip', '4.1.0'
gem 'papercrop', :path => "../.."

group :assets do 
  gem 'sass-rails', '~> 4.0.0'
  gem 'uglifier', '>= 1.3.0'
  gem 'coffee-rails', '~> 4.0.0'
  gem 'therubyracer', platforms: :ruby
end
