source 'https://rubygems.org'

gem 'rails', '4.0.2'
gem 'sqlite3'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'paperclip', '4.1.0'
gem 'papercrop', :path => "../.."

group :assets do 
  gem 'sass-rails', '~> 4.0.0'
  gem 'uglifier', '>= 1.3.0'
  gem 'coffee-rails', '~> 4.0.0'
  gem 'therubyracer', platforms: :ruby
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

